//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportePE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cambiodetroquel
    {
        public int ID { get; set; }
        public Nullable<int> NO_RECETA { get; set; }
        public Nullable<int> IDLINEA { get; set; }
        public string NOMBRE { get; set; }
        public System.DateTime INICIO { get; set; }
        public Nullable<System.DateTime> FIN { get; set; }
        public Nullable<System.DateTime> RUN { get; set; }
        public Nullable<int> TOTAL { get; set; }
        public string MODELO { get; set; }
        public Nullable<int> TOTALHTH { get; set; }
        public bool BANDERA { get; set; }
    }
}
