//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportePE.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CSL_CON_OPCEntities : DbContext
    {
        public CSL_CON_OPCEntities()
            : base("name=CSL_CON_OPCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cambiodetroquel> Cambiodetroquels { get; set; }
        public virtual DbSet<PRENSAS_Cat_NombresLinea> PRENSAS_Cat_NombresLinea { get; set; }
        public virtual DbSet<vw_CambiodeTroquel> vw_CambiodeTroquel { get; set; }
    }
}
