//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportePE.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CSL_CON_OPCEntities : DbContext
    {
        public CSL_CON_OPCEntities()
            : base("name=CSL_CON_OPCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cambiodetroquel> Cambiodetroquels { get; set; }
        public virtual DbSet<PRENSAS_Cat_NombresLinea> PRENSAS_Cat_NombresLinea { get; set; }
    }
}
