//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportePE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRENSAS_Cat_NombresLinea
    {
        public int IdPrensa { get; set; }
        public string Descripcion { get; set; }
        public string Trabajando { get; set; }
        public string Alias { get; set; }
        public string Maquina { get; set; }
        public string Tipo_Turno { get; set; }
        public string Area { get; set; }
        public Nullable<bool> ReporteoSAP { get; set; }
        public Nullable<int> MaxReport { get; set; }
        public Nullable<int> VelocidadGenerica { get; set; }
    }
}
