//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportePE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_CambiodeTroquel
    {
        public int ID { get; set; }
        public Nullable<int> NO_RECETA { get; set; }
        public Nullable<int> IDLINEA { get; set; }
        public string NOMBRE { get; set; }
        public System.DateTime INICIO { get; set; }
        public Nullable<System.DateTime> FIN { get; set; }
        public Nullable<System.DateTime> RUN { get; set; }
        public Nullable<int> TOTAL { get; set; }
        public string MODELO { get; set; }
        public Nullable<int> TOTALHTH { get; set; }
        public bool BANDERA { get; set; }
        public string NoParte { get; set; }
    }
}
